using AIQueryPlatform.Api.Models;
using AIQueryPlatform.Api.Models.DTOs;
using AIQueryPlatform.Api.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace AIQueryPlatform.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class QueryController : ControllerBase
{
    private readonly IQueryOrchestrationService _orchestrationService;
    private readonly IIntelligenceLayerService _intelligenceLayerService;
    private readonly IReportingService _reportingService;
    private readonly TenantContext _tenantContext;
    private readonly ILogger<QueryController> _logger;

    // JSON serializer options for streaming with enum string conversion
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Converters = { new JsonStringEnumConverter() }
    };

    public QueryController(
        IQueryOrchestrationService orchestrationService,
        IIntelligenceLayerService intelligenceLayerService,
        IReportingService reportingService,
        TenantContext tenantContext,
        ILogger<QueryController> logger)
    {
        _orchestrationService = orchestrationService;
        _intelligenceLayerService = intelligenceLayerService;
        _reportingService = reportingService;
        _tenantContext = tenantContext;
        _logger = logger;
    }

    /// <summary>
    /// Execute natural language query with streaming response (NDJSON)
    /// </summary>
    [HttpPost("execute-stream")]
    [Produces("application/x-ndjson")]
    public async IAsyncEnumerable<string> ExecuteStreamAsync([FromBody] QueryRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Query))
        {
            yield return JsonSerializer.Serialize(new StreamEvent
            {
                Type = "error",
                Message = "Query cannot be empty"
            }, JsonOptions);
            yield break;
        }

        await foreach (var streamEvent in _orchestrationService.ExecuteQueryStreamAsync(request.Query))
        {
            yield return JsonSerializer.Serialize(streamEvent, JsonOptions);
        }
    }

    /// <summary>
    /// Execute natural language query (non-streaming)
    /// </summary>
    [HttpPost("execute")]
    [ProducesResponseType(typeof(QueryResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<QueryResponse>> ExecuteAsync([FromBody] QueryRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Query))
        {
            return BadRequest(new { error = "Query cannot be empty" });
        }

        var response = await _orchestrationService.ExecuteQueryAsync(request.Query);

        if (!response.Success)
        {
            return BadRequest(response);
        }

        return Ok(response);
    }

    /// <summary>
    /// Generate PDF report from natural language query
    /// </summary>
    [HttpPost("generate-report")]
    [ProducesResponseType(typeof(FileContentResult), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> GenerateReportAsync([FromBody] ReportRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Query))
        {
            return BadRequest(new { error = "Query cannot be empty" });
        }

        if (!_tenantContext.HasTenant)
        {
            return Unauthorized(new { error = "No tenant context" });
        }

        var tenant = _tenantContext.CurrentTenant!;

        // Execute query
        var response = await _orchestrationService.ExecuteQueryAsync(request.Query);

        if (!response.Success || response.Result == null)
        {
            return BadRequest(new { error = response.ErrorMessage ?? "Query execution failed" });
        }

        // Use chart data already generated by orchestration service
        var chartData = response.ChartData;

        // Generate PDF
        var reportTitle = request.ReportTitle ?? "Query Report";
        var pdfBytes = await _reportingService.GeneratePdfReportAsync(
            response.Result,
            reportTitle,
            tenant,
            chartData);

        return File(pdfBytes, "application/pdf", $"{reportTitle.Replace(" ", "_")}.pdf");
    }

    /// <summary>
    /// Convert query result to chart data
    /// </summary>
    [HttpPost("to-chart")]
    [ProducesResponseType(typeof(ChartData), StatusCodes.Status200OK)]
    public async Task<ActionResult<ChartData>> ConvertToChartAsync([FromBody] QueryRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Query))
        {
            return BadRequest(new { error = "Query cannot be empty" });
        }

        var response = await _orchestrationService.ExecuteQueryAsync(request.Query);

        if (!response.Success || response.Result == null)
        {
            return BadRequest(new { error = response.ErrorMessage ?? "Query execution failed" });
        }

        var chartData = _intelligenceLayerService.ConvertToChartData(response.Result);

        if (chartData == null)
        {
            return BadRequest(new { error = "Data not suitable for chart visualization" });
        }

        return Ok(chartData);
    }
}
